version: "3.9"
volumes:
  my-volume:
    external: true
networks:
  default:
    external:
      name: matching

services:  
  frontend:
    build : .
    container_name: front-end 
    ports:
      - 8084:80
    networks:
      default:
        aliases:
          - frontend
